# Generated by Django 4.2 on 2023-05-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='librarian_table',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='reader_table',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('arrears', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='recommend_table',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('book_num', models.IntegerField()),
                ('admin_operation', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='未处理', max_length=20)),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myLibrary.reader_table')),
            ],
        ),
        migrations.CreateModel(
            name='booklist_table',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fig/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('vedio', models.FileField(null=True, upload_to='vedio/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLibrary.librarian_table')),
            ],
        ),
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_location', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLibrary.booklist_table')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLibrary.librarian_table')),
            ],
        ),
        migrations.CreateModel(
            name='reservation_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('take_date', models.DateTimeField()),
                ('reservation_status', models.CharField(default='未处理', max_length=20)),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myLibrary.book_table')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLibrary.booklist_table')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLibrary.reader_table')),
            ],
            options={
                'unique_together': {('reader_id', 'isbn', 'reservation_date')},
            },
        ),
        migrations.CreateModel(
            name='borrow_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_time', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myLibrary.book_table')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myLibrary.reader_table')),
            ],
            options={
                'unique_together': {('reader_id', 'book_id', 'borrowing_time')},
            },
        ),
    ]
