# Generated by Django 4.2 on 2023-06-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend_table',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recommend_table',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='recommend_table',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='recommend_table',
            name='publisher',
        ),
    ]
