# Generated by Django 4.2 on 2023-06-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0002_remove_recommend_table_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation_table',
            unique_together={('reader_id', 'book_id', 'reservation_date')},
        ),
        migrations.RemoveField(
            model_name='reservation_table',
            name='isbn',
        ),
    ]
