# Generated by Django 4.2 on 2023-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0003_alter_reservation_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader_table',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
